name: CI Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  integration:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v4

      - name: Setup environment variables
        run: cp .env.example .env

      - name: Install dependencies
        run: make install-deps && make deps

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: markarddev/wordka

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Build and push latest
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: markarddev/wordka:latest
          labels: ${{ steps.meta.outputs.labels }}
