name: Parse words from bezbukv

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Setup environment variables
        run: cp .env.example .env

      - name: Download modules
        run: go mod download

      - name: Build
        env:
          APP_ENV: "${{ vars.APP_ENV }}"
          PG_DB: "${{ secrets.PG_DB }}"
          PG_USER: "${{ secrets.PG_USER }}"
          PG_PASS: "${{ secrets.PG_PASS }}"
          PG_PORT: "${{ secrets.PG_PORT }}"
          PG_HOST: "${{ secrets.PG_HOST }}"
        run: CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -tags migrate -o bin/parser_bezbukv ./cmd/parser/bezbukv

      - name: Parse
        run: bin/parser_bezbukv
